// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using Tournament.Data;

namespace Tournament.Data.Migrations
{
    [DbContext(typeof(TournamentDbContext))]
    [Migration("20180401140258_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Tournament.Data.Entities.SteamUserInfo", b =>
                {
                    b.Property<int>("SteamUserInfoId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("SteamToken");

                    b.Property<int>("UserId");

                    b.HasKey("SteamUserInfoId");

                    b.ToTable("SteamUserInfos");
                });

            modelBuilder.Entity("Tournament.Data.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("UserName");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
